
# /Users/inada-n/work/idlite/idlite/parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'\xb5\xd9\x83M?-\x07\xf3,:\xb4E\x9e\xd6\r\x93'
    
_lr_action_items = {'<':([10,],[16,]),'CLASS':([0,1,2,4,12,],[-1,-10,3,-9,-2,]),'{':([5,],[6,]),'LIST':([6,7,8,13,14,17,],[-1,-4,10,-3,-7,-8,]),'ID':([3,6,7,8,9,11,13,14,15,16,17,19,],[5,-1,-4,11,14,-5,-3,-7,17,18,-8,-6,]),'?':([9,11,19,],[15,-5,-6,]),'$end':([0,1,2,4,12,],[-1,-10,0,-9,-2,]),'}':([6,7,8,13,14,17,],[-1,-4,12,-3,-7,-8,]),'>':([18,],[19,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'empty':([0,6,],[1,7,]),'type':([8,],[9,]),'fields':([6,],[8,]),'field':([8,],[13,]),'class':([2,],[4,]),'spec':([0,],[2,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> spec","S'",1,None,None,None),
  ('empty -> <empty>','empty',0,'p_empty','/Users/inada-n/work/idlite/idlite/parser.py',42),
  ('class -> CLASS ID { fields }','class',5,'p_class','/Users/inada-n/work/idlite/idlite/parser.py',46),
  ('fields -> fields field','fields',2,'p_fields','/Users/inada-n/work/idlite/idlite/parser.py',51),
  ('fields -> empty','fields',1,'p_fields','/Users/inada-n/work/idlite/idlite/parser.py',52),
  ('type -> ID','type',1,'p_type','/Users/inada-n/work/idlite/idlite/parser.py',62),
  ('type -> LIST < ID >','type',4,'p_type','/Users/inada-n/work/idlite/idlite/parser.py',63),
  ('field -> type ID','field',2,'p_field','/Users/inada-n/work/idlite/idlite/parser.py',75),
  ('field -> type ? ID','field',3,'p_field','/Users/inada-n/work/idlite/idlite/parser.py',76),
  ('spec -> spec class','spec',2,'p_spec','/Users/inada-n/work/idlite/idlite/parser.py',87),
  ('spec -> empty','spec',1,'p_spec','/Users/inada-n/work/idlite/idlite/parser.py',88),
]
